### ISSUE TITLE
E2E(FE) fail due to manager  sorting in the policy api

### ISSUE THREAD

**Issue by bpedersen2** [SciCatProject/backend#1013]
See https://github.com/SciCatProject/frontend/actions/runs/7538055162/job/20517946937?pr=1366

This is a fatal error in the E2E tests

```
 [Nest] 1  - 01/16/2024, 7:00:48 AM   ERROR [ExceptionsHandler] Invalid sort value: { manager asc: undefined }
backend_1           | TypeError: Invalid sort value: { manager asc: undefined }
backend_1           |     at _handleSortValue (/home/node/app/node_modules/mongoose/lib/query.js:2908:9)
backend_1           |     at Query.sort (/home/node/app/node_modules/mongoose/lib/query.js:2877:19)
backend_1           |     at PoliciesService.findAll (/home/node/app/dist/policies/policies.service.js:93:14)
backend_1           |     at PoliciesController.findAll (/home/node/app/dist/policies/policies.controller.js:83:37)
backend_1           |     at /home/node/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
backend_1           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
backend_1           |     at async /home/node/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
backend_1           |     at async /home/node/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
backend_1           |     at async /home/node/app/node_modules/@nestjs/core/router/router-explorer.js:166:17

```

**Comment by bpedersen2** [comment]
maybe related to mongoose 8, check e.g. https://copyprogramming.com/howto/error-sort-only-takes-1-argument-mongoose
