### ISSUE TITLE
Latest SDK generation on master push fail

### ISSUE THREAD

**Issue by Junjiequan** [SciCatProject/backend#1452]
openapi SDK generator throws the following error for the push on master branch.
The issue is most likely is due to the `required: false` in  published-data.schema.ts file.

```

Digest: sha256:7b4d65f91150ab7a572d7ee6835795ecad7a62e5d694f0685c8dbc4d29c41d20
Status: Downloaded newer image for openapitools/openapi-generator-cli:latest
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 12, Warning count: 0
Errors: 
	-paths.For path parameter sizeOfArchive the required value should be true
	-paths.For path parameter thumbnail the required value should be true
	-paths.For path parameter downloadLink the required value should be true
	-paths.For path parameter authors the required value should be true
	-paths.For path parameter affiliation the required value should be true
	-paths.For path parameter registeredTime the required value should be true
	-paths.For path parameter relatedPublications the required value should be true
	-paths.For path parameter url the required value should be true
	-paths.For path parameter scicatUser the required value should be true
	-paths.For path parameter doi the required value should be true
	-paths.For path parameter status the required value should be true
	-paths.For path parameter numberOfFiles the required value should be true

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:[74](https://github.com/SciCatProject/scicat-backend-next/actions/runs/11461049498/job/31893694382#step:4:76)4)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

```

**Comment by Junjiequan** [comment]
Fixed on PR #1455
